### PR TITLE
two CronTab with the same crontab command should be equal

### PR DESCRIPTION
**Pull request by timfeirg**
Fantastic library!

I've been using `parse-crontab` in my own project, and I aim to write tests to see if the program had successfully extracted the right crontab command, so I figured it can be handy to have `assert A.crontab == Crontab('* * * * *')` to see if the parsing results were right.

### CODE REVIEW

**Comment by josiahcarlson** [comment]
I've never had the desire/need to compare schedules (or verify that something picked up the right schedule; Crontab doesn't do magic stuff as a general rule).

Why require that the schedule string be equal for this case? Would it be better if something like `'5/30 * * * *'` was equal to `'5,35 * * * *'`, or for a more involved example, `5/15 * * * *` == `5,20,35,50 * * * *`? If so, it would be better to compare the _Matcher() objects for equality by what they accept. Thoughts?

**Comment by timfeirg** [comment]
This would be the right thing to do, I'll look at the code to see how this could be implemented.

**Comment by josiahcarlson** [comment]
`_Matcher()` objects only have 2 attributes worth comparing; `.any` for `*`/`?` items, and `.accepted` for the actual values when `.any` is `False`.

**Comment by josiahcarlson** [comment]
Ended up implementing this in a different way. See 0.22.8

Closing.

**Pull request closed without merging**
